# Generated by Django 4.2.19 on 2025-04-01 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('star', '0007_alter_star_birth_date_alter_star_categories_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='star',
            name='death_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата смерти'),
        ),
    ]
